# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feelight.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 491))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Desktop/WhatsApp Image 2025-04-28 at 23.50.05.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 390, 100, 32))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.toolButton.setObjectName("toolButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 40, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 100, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 170, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(270, 210, 99, 20))
        self.radioButton.setStyleSheet("color: rgb(236, 127, 255);\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 300, 99, 20))
        self.radioButton_2.setStyleSheet("color: rgb(255, 149, 100);\n"
"")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(270, 240, 99, 20))
        self.radioButton_3.setStyleSheet("color: rgb(141, 170, 255);\n"
"")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(270, 270, 99, 20))
        self.radioButton_4.setStyleSheet("color: rgb(255, 92, 57);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(270, 330, 99, 20))
        self.radioButton_5.setStyleSheet("color: rgb(166, 106, 255);\n"
"")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(270, 360, 171, 20))
        self.radioButton_6.setStyleSheet("color: rgb(99, 0, 113);")
        self.radioButton_6.setObjectName("radioButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.toolButton.setText(_translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:64pt; color:#ffffff;\">FEELIGHT</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">MOOD THROUGH WORDS</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">How are you feeling today?</span></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Happy"))
        self.radioButton_2.setText(_translate("MainWindow", "Calm"))
        self.radioButton_3.setText(_translate("MainWindow", "Sad"))
        self.radioButton_4.setText(_translate("MainWindow", "Angry"))
        self.radioButton_5.setText(_translate("MainWindow", "Anxious"))
        self.radioButton_6.setText(_translate("MainWindow", "Explore more emotions"))
