# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ikincifeel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 781, 491))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Desktop/WhatsApp Image 2025-04-28 at 23.50.05.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.toolButton_1 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_1.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.toolButton_1.setObjectName("toolButton_1")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 350, 131, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 99, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 99, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 30, 131, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 131, 461))
        self.listWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 131, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 260, 131, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 110, 131, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(0, 180, 131, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 210, 131, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 300, 131, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 140, 241, 31))
        self.label_6.setObjectName("label_6")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(220, 90, 461, 271))
        self.listWidget_2.setStyleSheet("QListWidget {\n"
"    background-color: rgb(255, 249, 236);\n"
"    color: #4b4b4b;\n"
"    border: 1px solid #d3d3d3;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(240, 224, 219);\n"
"    color: black;\n"
"}\n"
"rgb(255, 249, 236)")
        self.listWidget_2.setObjectName("listWidget_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(280, 200, 341, 23))
        self.progressBar.setStyleSheet("color: rgb(255, 170, 224);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 230, 371, 91))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, 50, 58, 16))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_5.raise_()
        self.listWidget.raise_()
        self.toolButton_1.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_6.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.pushButton_5.raise_()
        self.groupBox.raise_()
        self.listWidget_2.raise_()
        self.label_6.raise_()
        self.progressBar.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_1.setText(_translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "theme "))
        self.radioButton.setText(_translate("MainWindow", "light "))
        self.radioButton_2.setText(_translate("MainWindow", "dark "))
        self.pushButton_6.setText(_translate("MainWindow", "view mood log"))
        self.pushButton_2.setText(_translate("MainWindow", "customize"))
        self.pushButton_3.setText(_translate("MainWindow", "log out"))
        self.pushButton_4.setText(_translate("MainWindow", "mood patterns"))
        self.checkBox.setText(_translate("MainWindow", "save changes"))
        self.checkBox_2.setText(_translate("MainWindow", "reset to defaults"))
        self.pushButton_5.setText(_translate("MainWindow", "exit ↩️"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#515151;\">Detected Mood: </span><span style=\" font-size:24pt; color:#ff95ca;\">Happy</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Yay, we’re so glad to hear that! The color of happiness — <span style=\" color:#ff95ca;\">pink</span> — is loading just for you. Feel free to explore and match your own emotions with your favorite colors!</p></body></html>"))
